import turtle
from turtle import *
t=Turtle()
# t.color(' black')
style = ('Arial', 25, 'normal')
t.write("MASAI SCHOOL!\n\nNilesh Khairnar\n Cap04_029",font=style,align='right')
t.hideturtle()
wn=Screen()
wn.title("CREATE STAR")
wn.bgcolor("light blue")
t.shape()
t.color("black","orange")
t.begin_fill()
t.left(0)
t.forward(200)
t.left(145)
t.forward(200)
t.left(150)
t.forward(200)
t.left(145)
t.forward(200)
t.home()
t.end_fill()
done()